.. raw:: html

   <!-- NB: using raw:: directive in order to accurately tag metadata -->

     <p><a rel="author"
           href="http://champin.net/#pa"
           >Pierre-Antoine Champin</a>
     & <a rel="author"
           href="http://liris.cnrs.fr/~mmrissa"
           >Michael Mrissa</a></p>
     <address>Département Informatique,
       <a href="http://iut.univ-lyon1.fr/">IUT Lyon 1</a></address>

     <p><a rel="license"
        href="http://creativecommons.org/licenses/by-sa/3.0/fr/deed.fr">
        <img alt="Creative Commons License" style="border-width:0"
             src="_static/cc.png" /></a></p>

     <p class="license">Ce travail est sous licence
     <a rel="license"
        href="http://creativecommons.org/licenses/by-sa/3.0/fr/deed.fr">
        Creative Commons Attribution-ShareAlike 3.0 France</a>.</p>
